from pathlib import Path

import pytest
from pydantic import ValidationError

from cron_pydantic import CronConfiguration, load_config


def test_user_crontab_round_trip() -> None:
    configuration = CronConfiguration.model_validate(
        {
            "environment": {"PATH": "/usr/local/bin:/usr/bin", "GREETING": 'hello "cron"'},
            "job": {
                "backup": {"schedule": "0 2 * * *", "command": "/opt/bin/backup"},
                "cleanup": {"schedule": "@weekly", "command": "/opt/bin/cleanup", "enabled": False},
            },
        }
    )

    rendered = configuration.to_cron()

    assert rendered == (
        "# Generated by cron-pydantic\n"
        "PATH=/usr/local/bin:/usr/bin\n"
        'GREETING="hello \\"cron\\""\n'
        "\n"
        "# cron-pydantic: backup\n"
        "0 2 * * * /opt/bin/backup\n"
        "# cron-pydantic: cleanup\n"
        "# @weekly /opt/bin/cleanup\n"
    )
    assert CronConfiguration.from_cron(rendered).model_dump(exclude={"path"}) == configuration.model_dump(exclude={"path"})


def test_system_crontab_round_trip() -> None:
    contents = """# an unmanaged comment
SHELL=/bin/bash
# cron-pydantic: report
30 6 * * mon app /opt/bin/report --weekly
# cron-pydantic: bootstrap
@reboot root /opt/bin/bootstrap
"""

    configuration = CronConfiguration.from_cron(contents, system=True)

    assert configuration.job["report"].user == "app"
    assert configuration.job["bootstrap"].command == "/opt/bin/bootstrap"
    assert CronConfiguration.from_cron(configuration.to_cron(), system=True) == configuration


def test_parser_names_unmanaged_jobs() -> None:
    configuration = CronConfiguration.from_cron("#comment\n0 0 * * * first\n@daily second\n")

    assert list(configuration.job) == ["job-1", "job-2"]


def test_parser_accepts_single_quoted_environment_value() -> None:
    configuration = CronConfiguration.from_cron("MAILTO='cron admin'\n")

    assert configuration.environment == {"MAILTO": "cron admin"}


@pytest.mark.parametrize("line", ["not a cron line", "@daily"])
def test_parser_rejects_invalid_line(line: str) -> None:
    with pytest.raises(ValueError, match="invalid crontab line"):
        CronConfiguration.from_cron(line)


def test_system_configuration_requires_job_users() -> None:
    with pytest.raises(ValidationError, match="require a user"):
        CronConfiguration.model_validate({"system": True, "job": {"backup": {"schedule": "@daily", "command": "backup"}}})


def test_configuration_rejects_invalid_environment_name() -> None:
    with pytest.raises(ValidationError, match="invalid environment"):
        CronConfiguration(job={}, environment={"INVALID-NAME": "value"})


def test_write_requires_path() -> None:
    with pytest.raises(ValueError, match="path is required"):
        CronConfiguration(job={}).write()


def test_write_and_load_crontab(tmp_path: Path) -> None:
    destination = tmp_path / "nested" / "crontab"
    configuration = CronConfiguration(job={"backup": {"schedule": "@daily", "command": "backup"}}, path=destination)

    assert configuration.write() == destination

    loaded = load_config(destination)
    assert loaded.job == configuration.job
    assert loaded.path == destination


def test_write_to_explicit_path(tmp_path: Path) -> None:
    destination = tmp_path / "crontab"

    assert CronConfiguration(job={}).write(destination) == destination


def test_load_yaml(tmp_path: Path) -> None:
    source = tmp_path / "cron.yaml"
    source.write_text("job:\n  backup:\n    schedule: '@daily'\n    command: backup\n")

    configuration = CronConfiguration.load(source)

    assert configuration.job["backup"].to_cron() == "@daily backup"
